export const all_products = [
  {
    name: "MiniSplit de 12,000BTU",
    price: "35.00",
    img: "mantto1.webp",
    category: "Minisplit",
    color: "rosa",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "Eco-Enfriador Kabel",
    price: "15.00",
    img: "mantto2.webp",
    category: "Kabel",
    color: "roxo",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "Aire acondicionado tipo ventana",
    price: "24.00",
    img: "mantto3.webp",
    category: "Minisplit",
    color: "verde",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "Aire acondicionado tipo Central 5 TON",
    price: "110.00",
    img: "mantto4.webp",
    category: "Tipo Central",
    color: "amarelo",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "MiniSplit de 18,000BTU",
    price: "35.00",
    img: "mantto1.webp",
    category: "Minisplit",
    color: "verde",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "MiniSplit de 24,000BTU",
    price: "35.00",
    img: "mantto1.webp",
    category: "Minisplit",
    description: "Mantenimiento preventivo.",
    color: "verde",
  },
  {
    name: "MiniSplit de 36,000BTU",
    price: "35.00",
    img: "mantto1.webp",
    category: "Minisplit",
    color: "roxo",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "Equipo por agregar",
    price: "38.95",
    img: "stock.webp",
    category: "flores",
    color: "amarelo",
    description: "Aqui la descripción de el producto.",
  },
  {
    name: "Equipo por agregar",
    price: "25.99",
    img: "stock.webp",
    category: "flores",
    description: "Aqui la descripción de el producto.",
    color: "rosa",
  },
  {
    name: "Equipo por agregar",
    price: "42.75",
    img: "stock.webp",
    category: "flores",
    color: "branco",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Equipo por agregar",
    price: "49.99",
    img: "stock.webp",
    category: "flores",
    color: "amarelo",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Equipo por agregar",
    price: "75.10",
    img: "stock.webp",
    category: "flores",
    color: "azul",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Equipo por agregar",
    price: "17.45",
    img: "stock.webp",
    category: "cactos",
    description: "Aqui la descripción de el producto.",
    color: "verde",
  },
  {
    name: "Equipo por agregar",
    price: "33.59",
    img: "stock.webp",
    category: "flores",
    color: "amarelo",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Equipo por agregar",
    price: "38.25",
    img: "stock.webp",
    category: "flores",
    description: "Aqui la descripción de el producto.",
    color: "laranja",
  },
  {
    name: "Equipo por agregar",
    price: "48.60",
    img: "stock.webp",
    category: "outros",
    color: "verde",
    description:
      "Aqui la descripción de el producto.",
  },
];
