export const all_products = [
  {
    name: "Minisplit de 12,000BTU hasta 18,000BTU",
    price: "35",
    img: "mantto1.webp",
    category: "flores",
    color: "rosa",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "Eco-Enfriador Kabel",
    price: "15",
    img: "mantto2.webp",
    category: "flores",
    color: "roxo",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "Aire acondicionado tipo ventana",
    price: "24",
    img: "mantto3.webp",
    category: "cactos",
    color: "verde",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "Aire acondicionado tipo Central",
    price: "110",
    img: "img3.webp",
    category: "flores",
    color: "amarelo",
    description: "Mantenimiento preventivo.",
  },
  {
    name: "Quisque",
    price: "36.49",
    img: "img4.webp",
    category: "cactos",
    color: "verde",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Maecenas elementum",
    price: "27.79",
    img: "img5.webp",
    category: "cactos",
    description: "Aqui la descripción de el producto.",
    color: "verde",
  },
  {
    name: "Phasellus mattis",
    price: "51.49",
    img: "img6.webp",
    category: "flores",
    color: "roxo",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Ultrices",
    price: "38.95",
    img: "img48.webp",
    category: "flores",
    color: "amarelo",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Donec placerat",
    price: "25.99",
    img: "img8.webp",
    category: "flores",
    description: "Aqui la descripción de el producto.",
    color: "rosa",
  },
  {
    name: "Orci varius",
    price: "42.75",
    img: "img9.webp",
    category: "flores",
    color: "branco",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Mauris",
    price: "49.99",
    img: "img50.webp",
    category: "flores",
    color: "amarelo",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Cras sit",
    price: "75.10",
    img: "img10.webp",
    category: "flores",
    color: "azul",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Etiam",
    price: "17.45",
    img: "img11.webp",
    category: "cactos",
    description: "Aqui la descripción de el producto.",
    color: "verde",
  },
  {
    name: "Bibendum",
    price: "33.59",
    img: "img47.webp",
    category: "flores",
    color: "amarelo",
    description:
      "Aqui la descripción de el producto.",
  },
  {
    name: "Ullamcolorper augue",
    price: "38.25",
    img: "img12.webp",
    category: "flores",
    description: "Aqui la descripción de el producto.",
    color: "laranja",
  },
  {
    name: "Eget facilisis",
    price: "48.60",
    img: "img13.webp",
    category: "outros",
    color: "verde",
    description:
      "Aqui la descripción de el producto.",
  },
];
